FofbCc(0)
dbLoadRecords("db/scan_task.template", "PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH0, ADDR=0, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH1, ADDR=1, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH2, ADDR=2, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH3, ADDR=3, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH4, ADDR=4, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH5, ADDR=5, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH6, ADDR=6, PORT=FOFB_CC-0")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCFMC, FOFB_CHAN=CH7, ADDR=7, PORT=FOFB_CC-0")

FofbCc(1)
dbLoadRecords("db/scan_task.template", "PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH0, ADDR=0, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH1, ADDR=1, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH2, ADDR=2, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH3, ADDR=3, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH4, ADDR=4, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH5, ADDR=5, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH6, ADDR=6, PORT=FOFB_CC-1")
dbLoadRecords("db/fofb_cc_channel.template", "P=${P}, R=${R}, FOFB_CC=DCCP2P, FOFB_CHAN=CH7, ADDR=7, PORT=FOFB_CC-1")
