RtmLamp(0)
dbLoadRecords("db/scan_task.template", "PORT=RTMLAMP-0")

dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=M1:PS-FCH:,  PORT=RTMLAMP-0, ADDR=0")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=M1:PS-FCV:,  PORT=RTMLAMP-0, ADDR=1")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=M2:PS-FCH:,  PORT=RTMLAMP-0, ADDR=2")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=M2:PS-FCV:,  PORT=RTMLAMP-0, ADDR=3")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=C2:PS-FCH:,  PORT=RTMLAMP-0, ADDR=4")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=C2:PS-FCV:,  PORT=RTMLAMP-0, ADDR=5")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=C3:PS-FCH:,  PORT=RTMLAMP-0, ADDR=6")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=C3:PS-FCV:,  PORT=RTMLAMP-0, ADDR=7")

dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=XX:PS-FC08:, PORT=RTMLAMP-0, ADDR=8")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=XX:PS-FC09:, PORT=RTMLAMP-0, ADDR=9")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=XX:PS-FC10:, PORT=RTMLAMP-0, ADDR=10")
dbLoadRecords("db/rtmlamp.template", "P=${P}, R=${R}, S=${S}, RTM_CHAN=XX:PS-FC11:, PORT=RTMLAMP-0, ADDR=11")
